"""
IMPORTANTE -- este script es una grabación de Playwright codegen para uso
PUNTUAL y manual: antes de correrlo, reemplazá TU_CUIT_ACA, TU_CLAVE_FISCAL_ACA
y NOMBRE_DE_LA_EMPRESA_ACA por los datos reales a mano, y NUNCA los dejes
commiteados así en el repo (es público) -- se encontraron credenciales
reales de ARCA escritas acá y hubo que sacarlas.
"""
import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://auth.afip.gob.ar/contribuyente_/login.xhtml")
    page.get_by_role("spinbutton").click()
    page.get_by_role("spinbutton").fill("TU_CUIT_ACA")
    page.get_by_role("button", name="Siguiente").click()
    page.get_by_role("textbox", name="TU CLAVE").click()
    page.get_by_role("textbox", name="TU CLAVE").fill("TU_CLAVE_FISCAL_ACA")
    page.get_by_role("button", name="Ingresar").click()
    with page.expect_popup() as page1_info:
        page.locator("a").filter(has_text="Comprobantes en línea").click()
    page1 = page1_info.value
    page1.get_by_role("button", name="NOMBRE_DE_LA_EMPRESA_ACA").click()
    page1.get_by_role("button", name="Generar Comprobantes").click()
    page1.locator("#puntodeventa").select_option("2")
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="...").click()
    page1.get_by_role("cell", name="5").nth(3).click()
    page1.locator("#idconcepto").select_option("1")
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#idivareceptor").select_option("13")
    page1.locator("#idivareceptor").select_option("16")
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").fill("23421613869")
    page1.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page1.once("dialog", lambda dialog: dialog.dismiss())
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="< Volver").click()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#idivareceptor").select_option("13")
    page1.locator("#idivareceptor").select_option("16")
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").fill("23421613869")
    page1.locator("#nrodocreceptor").press("Tab")
    page1.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page1.once("dialog", lambda dialog: dialog.dismiss())
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="< Volver").click()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#idivareceptor").select_option("13")
    page1.locator("#idivareceptor").select_option("16")
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").fill("20253682982")
    page1.locator("#nrodocreceptor").press("Tab")
    page1.get_by_role("columnheader", name="Otros medios de pago electró").click()
    page1.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#detalle_descripcion1").click()
    page1.locator("#detalle_descripcion1").fill("chacinado")
    page1.locator("#detalle_precio1").click()
    page1.locator("#detalle_medida1").select_option("7")
    page1.once("dialog", lambda dialog: dialog.dismiss())
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#detalle_importe_bonificacion1").click()
    page1.locator("#detalle_importe_bonificacion1").fill("5000")
    page1.once("dialog", lambda dialog: dialog.dismiss())
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#detalle_cantidad1").click()
    page1.locator("#detalle_importe_bonificacion1").click()
    page1.locator("#detalle_importe_bonificacion1").fill("50000")
    page1.locator("#detalle_descripcion1").click()
    page1.locator("#detalle_subtotal11").click()
    page1.locator("#detalle_tipo_iva1").select_option("3")
    page1.locator("#detalle_tipo_iva1").select_option("5")
    page1.get_by_role("button", name="< Volver").click()
    page1.once("dialog", lambda dialog: dialog.dismiss())
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="< Volver").click()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").fill("20253682982")
    page1.locator("#nrodocreceptor").press("Tab")
    page1.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#detalle_descripcion1").click()
    page1.locator("#detalle_descripcion1").fill("chacinado")
    page1.locator("#detalle_precio1").click()
    page1.locator("#detalle_precio1").fill("5000")
    page1.locator("#detalle_medida1").select_option("7")
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="Menú Principal").click()
    page1.get_by_role("button", name="Generar Comprobantes").click()
    page1.locator("#puntodeventa").select_option("2")
    page1.locator("#universocomprobante").select_option("19")
    page1.get_by_role("cell", name="Factura B").click()
    page1.locator("#universocomprobante").select_option("10")
    page1.locator("#universocomprobante").select_option("11")
    page1.locator("#universocomprobante").select_option("12")
    page1.locator("#universocomprobante").select_option("13")
    page1.locator("#universocomprobante").select_option("19")
    page1.locator("#universocomprobante").select_option("21")
    page1.locator("#universocomprobante").select_option("23")
    page1.locator("#universocomprobante").select_option("25")
    page1.locator("#universocomprobante").select_option("111")
    page1.locator("#universocomprobante").select_option("112")
    page1.locator("#universocomprobante").select_option("113")
    page1.locator("#universocomprobante").select_option("114")
    page1.locator("#universocomprobante").select_option("115")
    page1.locator("#universocomprobante").select_option("116")
    page1.locator("#universocomprobante").select_option("117")
    page1.locator("#universocomprobante").select_option("118")
    page1.locator("#universocomprobante").select_option("119")
    page1.locator("#universocomprobante").select_option("10")
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idconcepto").select_option("1")
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#idivareceptor").select_option("13")
    page1.locator("#idivareceptor").select_option("16")
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").fill("20253682982")
    page1.locator("#nrodocreceptor").press("Tab")
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="< Volver").click()
    page1.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page1.once("dialog", lambda dialog: dialog.dismiss())
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").press("Tab")
    page1.get_by_role("button", name="< Volver").click()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#domicilioreceptor").click()
    page1.locator("#idivareceptor").select_option("6")
    page1.locator("#idivareceptor").select_option("13")
    page1.locator("#idivareceptor").select_option("16")
    page1.locator("#idivareceptor").select_option("1")
    page1.locator("#nrodocreceptor").click()
    page1.locator("#nrodocreceptor").fill("20253682982")
    page1.locator("#nrodocreceptor").press("Tab")
    page1.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page1.get_by_role("button", name="Continuar >").click()
    page1.locator("#detalle_descripcion1").click()
    page1.locator("#detalle_descripcion1").fill("chacinado")
    page1.locator("#detalle_medida1").select_option("7")
    page1.locator("#detalle_precio1").click()
    page1.locator("#detalle_precio1").fill("5000")
    page1.locator("#detalle_tipo_iva1").select_option("6")
    page1.locator("#detalle_tipo_iva1").select_option("5")
    page1.locator("#detalle_tipo_iva1").select_option("4")
    page1.locator("#detalle_tipo_iva1").select_option("8")
    page1.locator("#detalle_tipo_iva1").select_option("9")
    page1.locator("#detalle_tipo_iva1").select_option("3")
    page1.locator("#detalle_tipo_iva1").select_option("2")
    page1.locator("#detalle_tipo_iva1").select_option("1")
    page1.locator("#detalle_tipo_iva1").select_option("5")
    page1.get_by_role("button", name="Agregar línea descripción").click()
    page1.locator("#detalle_descripcion2").click()
    page1.locator("#detalle_descripcion2").fill("cortes de carne")
    page1.locator("#detalle_precio2").click()
    page1.locator("#detalle_medida2").select_option("7")
    page1.locator("#detalle_precio2").click()
    page1.locator("#detalle_precio2").fill("6000")
    page1.locator("#detalle_tipo_iva2").select_option("6")
    page1.locator("#detalle_tipo_iva2").select_option("5")
    page1.locator("#detalle_tipo_iva2").select_option("4")
    page1.locator("#detalle_tipo_iva2").select_option("8")
    page1.locator("#detalle_tipo_iva2").select_option("9")
    page1.locator("#detalle_tipo_iva2").select_option("3")
    page1.locator("#detalle_tipo_iva2").select_option("2")
    page1.locator("#detalle_tipo_iva2").select_option("1")
    page1.locator("#detalle_tipo_iva2").select_option("4")
    page1.get_by_role("button", name="Continuar >").click()
    page1.get_by_role("button", name="< Volver").click()
    page1.get_by_role("button", name="Menú Principal").click()
    page.locator("#userIconoChico").click()
    page.get_by_role("button", name=" Cerrar sesión").click()
    page1.close()
    page.get_by_role("spinbutton").click()
    page.get_by_role("spinbutton").click()
    page.get_by_role("spinbutton").click()
    page.get_by_role("spinbutton").fill("TU_CUIT_ACA")
    page.get_by_role("button", name="Siguiente").click()
    page.get_by_role("textbox", name="TU CLAVE").click()
    page.get_by_role("textbox", name="TU CLAVE").fill("TU_CLAVE_FISCAL_ACA")
    page.get_by_role("button", name="Ingresar").click()
    with page.expect_popup() as page2_info:
        page.locator("a").filter(has_text="Comprobantes en línea").click()
    page2 = page2_info.value
    page2.get_by_role("button", name="NOMBRE_DE_LA_EMPRESA_ACA").click()
    page2.get_by_role("button", name="Generar Comprobantes").click()
    page2.locator("#puntodeventa").select_option("2")
    page2.locator("#universocomprobante").select_option("19")
    page2.get_by_role("button", name="Continuar >").click()
    page2.locator("#idconcepto").select_option("1")
    page2.get_by_role("button", name="Continuar >").click()
    page2.locator("#idivareceptor").select_option("4")
    page2.locator("#idivareceptor").select_option("5")
    page2.locator("#idivareceptor").select_option("7")
    page2.locator("#idivareceptor").select_option("8")
    page2.locator("#idivareceptor").select_option("9")
    page2.locator("#idivareceptor").select_option("10")
    page2.locator("#idivareceptor").select_option("15")
    page2.locator("#idivareceptor").select_option("5")
    page2.locator("#idtipodocreceptor").select_option("96")
    page2.get_by_role("checkbox", name="Otros medios de pago electró").check()
    page2.get_by_role("button", name="Continuar >").click()
    page2.locator("#detalle_descripcion1").click()
    page2.locator("#detalle_descripcion1").fill("chacinado")
    page2.locator("#idoperacion").click()
    page2.locator("#detalle_medida1").select_option("7")
    page2.locator("#detalle_precio1").click()
    page2.locator("#detalle_precio1").fill("5000")
    page2.locator("#detalle_tipo_iva1").select_option("5")
    page2.get_by_role("button", name="Continuar >").click()
    page2.get_by_role("button", name="Menú Principal").click()
    page2.close()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
