"""Agregar Google Drive por empresa

Revision ID: 50102b0d53fc
Revises: e86af15507ba
Create Date: 2026-08-30 02:18:46.766514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50102b0d53fc'
down_revision = 'e86af15507ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_drive_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_drive_token_cifrado', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('google_drive_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('google_drive_carpeta_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('registros_subida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_drive_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_subida', schema=None) as batch_op:
        batch_op.drop_column('archivo_drive_id')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('google_drive_carpeta_id')
        batch_op.drop_column('google_drive_email')
        batch_op.drop_column('google_drive_token_cifrado')

    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.drop_column('archivo_drive_id')

    # ### end Alembic commands ###
