"""Agregar facturado_en a Comprobante (cuándo se facturó de verdad)

Revision ID: 977821d0f9bd
Revises: f003d1c9e3bc
Create Date: 2026-08-31 22:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977821d0f9bd'
down_revision = 'f003d1c9e3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facturado_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.drop_column('facturado_en')
    # ### end Alembic commands ###
