"""Estado inicial: usuarios, empresas, comprobantes, registros de subida

Revision ID: e86af15507ba
Revises: 
Create Date: 2026-08-29 23:26:32.450460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86af15507ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_razon_social', sa.String(length=200), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=150), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_interno', sa.String(length=200), nullable=True),
    sa.Column('razon_social_arca', sa.String(length=200), nullable=True),
    sa.Column('cuil_arca', sa.String(length=20), nullable=True),
    sa.Column('password_arca_cifrada', sa.LargeBinary(), nullable=True),
    sa.Column('config_tipo_comprobante', sa.String(length=80), nullable=True),
    sa.Column('puntos_venta_disponibles', sa.String(length=200), nullable=True),
    sa.Column('config_punto_venta', sa.String(length=10), nullable=True),
    sa.Column('config_concepto', sa.String(length=10), nullable=True),
    sa.Column('config_condicion_iva', sa.String(length=80), nullable=True),
    sa.Column('config_tipo_doc_receptor', sa.String(length=80), nullable=True),
    sa.Column('config_condicion_venta', sa.String(length=300), nullable=True),
    sa.Column('config_producto_servicio', sa.String(length=300), nullable=True),
    sa.Column('descripciones_disponibles', sa.String(length=600), nullable=True),
    sa.Column('config_descripcion_aleatoria', sa.Boolean(), nullable=True),
    sa.Column('config_unidad_medida', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=200), nullable=True),
    sa.Column('id_transaccion', sa.String(length=120), nullable=True),
    sa.Column('punto_venta', sa.String(length=10), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=80), nullable=True),
    sa.Column('concepto', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('unidad_medida', sa.String(length=80), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=30), nullable=True),
    sa.Column('cuit_receptor', sa.String(length=20), nullable=True),
    sa.Column('nombre_razon_social', sa.String(length=200), nullable=True),
    sa.Column('nombre_remitente', sa.String(length=200), nullable=True),
    sa.Column('fecha_comprobante', sa.String(length=20), nullable=True),
    sa.Column('medio_pago_detectado', sa.String(length=20), nullable=True),
    sa.Column('condicion_iva', sa.String(length=80), nullable=True),
    sa.Column('condicion_venta', sa.String(length=80), nullable=True),
    sa.Column('tipo_pago', sa.String(length=80), nullable=True),
    sa.Column('numero_pago', sa.String(length=80), nullable=True),
    sa.Column('fecha_desde', sa.String(length=20), nullable=True),
    sa.Column('fecha_hasta', sa.String(length=20), nullable=True),
    sa.Column('importe_total', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('archivo_origen', sa.String(length=300), nullable=True),
    sa.Column('archivo_ruta', sa.String(length=400), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('error_facturacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id')
    )
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobantes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobantes_id_transaccion'), ['id_transaccion'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobantes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('registros_subida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('archivo_ruta', sa.String(length=400), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_subida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_subida_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_subida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_subida_empresa_id'))

    op.drop_table('registros_subida')
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobantes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_comprobantes_id_transaccion'))
        batch_op.drop_index(batch_op.f('ix_comprobantes_empresa_id'))

    op.drop_table('comprobantes')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_usuario_id'))

    op.drop_table('empresas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
