"""Agregar días atrás para fecha de emisión por defecto (por empresa)

Revision ID: f003d1c9e3bc
Revises: 50102b0d53fc
Create Date: 2026-08-31 04:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f003d1c9e3bc'
down_revision = '50102b0d53fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_dias_atras_fecha_emision', sa.Integer(), nullable=True, server_default='10'))

    # Las empresas ya existentes quedan explícitamente en 10 (el criterio que
    # ya se usaba antes hardcodeado), no en NULL -- así el comportamiento no
    # cambia para nadie hasta que alguien lo edite a mano.
    op.execute("UPDATE empresas SET config_dias_atras_fecha_emision = 10 WHERE config_dias_atras_fecha_emision IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('config_dias_atras_fecha_emision')
    # ### end Alembic commands ###
